lib/daily_vocabulary_web/router.ex
defmodule DailyVocabularyWeb.Router do
  use DailyVocabularyWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    # plug DailyVocabularyWeb.Plugs.SetUser
  end

  pipeline :api do
    plug :accepts, ["json"]
    post "/login", AuthController, :login
  end

  scope "/", DailyVocabularyWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
  end

  scope "/auth", DailyVocabularyWeb do
    pipe_through :browser

    get("/:provider", AuthController, :request)
    get("/:provider/callback", AuthController, :callback)
    post("/:provider/callback", AuthController, :callback)
    delete("/logout", AuthController, :delete)
  end

  # Other scopes may use custom stacks.
  # scope "/api", DailyVocabularyWeb do
  #   pipe_through :api
  # end
end

lib/daily_vocabulary/accounts/user.ex
defmodule DailyVocabulary.Accounts.User do
  use Ecto.Schema
  import Ecto.Changeset

  schema "users" do
    field :name, :string
    field :email, :string
    field :provider, :string
    field :token, :string
    field :password_hash, :string
    field :avatar, :string
    field :first_name, :string
    field :last_name, :string

    field :password, :string, virtual: true
    field :password_confirmation, :string, virtual: true

    timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [ :name, :email, :password, :password_confirmation, :provider, :token]) # Remove hash, add pw + pw confirmation
    |> validate_required([:email, :password, :password_confirmation]) # Remove hash, add pw + pw confirmation
    |> validate_format(:email, ~r/@/) # Check that email is valid
    |> validate_length(:password, min: 6) # Check that password length is >= 8
    |> validate_confirmation(:password) # Check that password === password_confirmation
    |> unique_constraint(:email)
  end
end

lib/daily_vocabulary/accounts/user_from_auth.ex
defmodule DailyVocabulary.Accounts.UserFromAuth do
  @moduledoc """
  Retrieve the user information from an auth request
  """
  require Logger
  require Poison

  alias Ueberauth.Auth

  def find_or_create(%Auth{} = auth) do
    IO.puts("AUTH>INFO")
    IO.inspect(auth.info.email)
    {:ok, basic_info(auth)}
  end

  defp basic_info(auth) do
    %{id: auth.uid, email: email_from_auth(auth)}
  end

  defp email_from_auth(auth) do
    if auth.info.email do
      auth.info.email
    else
      "XXXX@XXXX.com"
    end
  end

  defp name_from_auth(auth) do
  if auth.info.name do
    auth.info.name
  else
    name =
      [auth.info.first_name, auth.info.last_name]
      |> Enum.filter(&(&1 != nil and &1 != ""))

    if Enum.empty?(name) do
      auth.info.nickname
    else
      Enum.join(name, " ")
    end
  end
end
end

lib/daily_vocabulary/application.ex
defmodule DailyVocabulary.Application do
  use Application

  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  def start(_type, _args) do
    import Supervisor.Spec

    # Define workers and child supervisors to be supervised
    children = [
      # Start the Ecto repository
      supervisor(DailyVocabulary.Repo, []),
      # Start the endpoint when the application starts
      supervisor(DailyVocabularyWeb.Endpoint, []),
      # Start your own worker by calling: DailyVocabulary.Worker.start_link(arg1, arg2, arg3)
      # worker(DailyVocabulary.Worker, [arg1, arg2, arg3]),
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: DailyVocabulary.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    DailyVocabularyWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/daily_vocabulary/repo.ex
defmodule DailyVocabulary.Repo do
  use Ecto.Repo,
    otp_app: :daily_vocabulary,
    adapter: Ecto.Adapters.Postgres

  @doc """
  Dynamically loads the repository url from the
  DATABASE_URL environment variable.
  """
  def init(_, opts) do
    {:ok, Keyword.put(opts, :url, System.get_env("DATABASE_URL"))}
  end
end

lib/daily_vocabulary_web/controllers/auth_controller.ex
defmodule DailyVocabularyWeb.AuthController do
  use DailyVocabularyWeb, :controller
  alias DailyVocabulary.{Accounts.User}

  plug Ueberauth

  alias DailyVocabulary.Accounts.UserFromAuth

  alias Ueberauth.Strategy.Helpers

  def request(conn, _params) do
    render(conn, "request.html", callback_url: Helpers.callback_url(conn))
  end

  def delete(conn, _params) do
    conn
    |> put_flash(:info, "You have been logged out!")
    |> clear_session()
    |> redirect(to: "/")
  end

  def callback(%{assigns: %{ueberauth_failure: _fails}} = conn, _params) do
    conn
    |> put_flash(:error, "Failed to authenticate.")
    |> redirect(to: "/")
  end

  def callback(%{assigns: %{ueberauth_auth: auth}} = conn, _params) do
  # def callback(conn, _params) do
    IO.inspect(conn)
    case UserFromAuth.find_or_create(auth) do
      {:ok, user} ->
        conn
        |> put_flash(:info, "Successfully authenticated.")
        |> put_session(:current_user, user)
        |> configure_session(renew: true)
        |> redirect(to: "/")

      {:error, reason} ->
        conn
        |> put_flash(:error, reason)
        |> redirect(to: "/")
    end
  end

  def signout(conn, _params) do
        conn
        |> configure_session(drop: true)
        |> redirect(to: page_path(conn, :index))
  end
end

lib/daily_vocabulary_web/controllers/page_controller.ex
defmodule DailyVocabularyWeb.PageController do
  use DailyVocabularyWeb, :controller

  def index(conn, _params) do
    render conn, "index.html", current_user: get_session(conn, :current_user)
  end
end

lib/daily_vocabulary_web/views/auth_view.ex
defmodule DailyVocabularyWeb.AuthView do
  use DailyVocabularyWeb, :view
end

lib/daily_vocabulary_web/views/error_view.ex
defmodule DailyVocabularyWeb.ErrorView do
  use DailyVocabularyWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

lib/daily_vocabulary_web/views/layout_view.ex
defmodule DailyVocabularyWeb.LayoutView do
  use DailyVocabularyWeb, :view
end

lib/daily_vocabulary_web/views/page_view.ex
defmodule DailyVocabularyWeb.PageView do
  use DailyVocabularyWeb, :view
end

lib/daily_vocabulary_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Daily Vocabulary!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <!-- <header class="header"></header> -->

      <p class="my-alert alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="my-alert alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <%= render @view_module, @view_template, assigns %>

      <!-- <main role="main"></main> -->

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/daily_vocabulary_web/templates/page/index.html.eex
<div class="row justify-content-center align-self-center">
  <div class="col-sm-4 col-md-4">
    <div class="jumbotron vertical-center">
      <%= if @current_user do %>
        <h2>Welcome, <%= @current_user.email %>!</h2>
        <%= link "Logout", to: auth_path(@conn, :delete), method: :delete, class: "btn btn-primary btn-lg" %>
        <br>
      <% else %>

        <a class="btn btn-default btn-lg" href="/auth/vkontakte">
          <i class="fa fa-github"></i>
          Sign in with Vkontakte
        </a>

        <a class="btn btn-secondary btn-lg" href="/auth/facebook">
          <i class="fa fa-facebook"></i>
          Sign in with Facebook
        </a>

       <a class="btn btn-secondary btn-lg" href="/auth/google">
        <i class="fa fa-google"></i>
        Sign in with Google
      </a>
      <% end %>
    </div>
  </div>
</div>